### Update all user's data
PUT http://localhost:8000/users/JohnSnow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMTc1MjQwOSwianRpIjoiNzUzNDlmNDgtOGFmZS00MjUzLWE5ODMtYmJlZWE3NmFiNWIwIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkpvaG5Tbm93IiwibmJmIjoxNzExNzUyNDA5LCJjc3JmIjoiZWEwYjM5ZGMtNWQ2OC00OTk4LWE5MjAtYmRhNTUyMGU5NzZiIiwiZXhwIjoxNzExNzUzMzA5fQ.LG8pJgCBvSySl05LLeRCsQjLseoI8cW6f6I8qboiRcw

{
    "name": "John",
    "surname": "Snow",
    "birthdate": "1813-03-15",
    "email": "gameofthrones@gmail.com",
    "phone": "+88005353535"
}

### Update user's email
PUT http://localhost:8000/users/JohnSnow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMTc1MjQwOSwianRpIjoiNzUzNDlmNDgtOGFmZS00MjUzLWE5ODMtYmJlZWE3NmFiNWIwIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkpvaG5Tbm93IiwibmJmIjoxNzExNzUyNDA5LCJjc3JmIjoiZWEwYjM5ZGMtNWQ2OC00OTk4LWE5MjAtYmRhNTUyMGU5NzZiIiwiZXhwIjoxNzExNzUzMzA5fQ.LG8pJgCBvSySl05LLeRCsQjLseoI8cW6f6I8qboiRcw

{
    "email": "somewhere@mail.ru"
}
