version: '3.8'
services:
  users_db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment: # TODO do not store parameters publicly
      MYSQL_DATABASE: 'usersdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db_data:/var/lib/mysql

  users-service:
    build: users/app
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    depends_on:
      - users_db
      - posts-service
      - kafka
    environment: # TODO do not store parameters publicly
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://user:password@users_db/usersdb"
      JWT_SECRET_KEY : "super_jwt_secret_key"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  posts_db:
    image: mongo:latest
    restart: always
    volumes:
      - posts_db_data:/data/db

  posts-service:
    build: ./posts/app
    ports:
      - "5300:5300"
    depends_on:
      - posts_db
    environment:
      MONGODB_URI: "mongodb://posts_db:27017"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181


volumes:
  db_data:
  posts_db_data:
  kafka_data:
