# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import statistics_pb2 as statistics__pb2


class StatisticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTotalViewsAndLikes = channel.unary_unary(
                '/statistics.StatisticsService/GetTotalViewsAndLikes',
                request_serializer=statistics__pb2.ViewsAndLikesRequest.SerializeToString,
                response_deserializer=statistics__pb2.ViewsAndLikesResponse.FromString,
                )
        self.GetTopPosts = channel.unary_unary(
                '/statistics.StatisticsService/GetTopPosts',
                request_serializer=statistics__pb2.TopPostsRequest.SerializeToString,
                response_deserializer=statistics__pb2.TopPostsResponse.FromString,
                )
        self.GetTopUsers = channel.unary_unary(
                '/statistics.StatisticsService/GetTopUsers',
                request_serializer=statistics__pb2.Empty.SerializeToString,
                response_deserializer=statistics__pb2.TopUsersResponse.FromString,
                )


class StatisticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTotalViewsAndLikes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTotalViewsAndLikes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalViewsAndLikes,
                    request_deserializer=statistics__pb2.ViewsAndLikesRequest.FromString,
                    response_serializer=statistics__pb2.ViewsAndLikesResponse.SerializeToString,
            ),
            'GetTopPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPosts,
                    request_deserializer=statistics__pb2.TopPostsRequest.FromString,
                    response_serializer=statistics__pb2.TopPostsResponse.SerializeToString,
            ),
            'GetTopUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsers,
                    request_deserializer=statistics__pb2.Empty.FromString,
                    response_serializer=statistics__pb2.TopUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statistics.StatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StatisticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTotalViewsAndLikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/statistics.StatisticsService/GetTotalViewsAndLikes',
            statistics__pb2.ViewsAndLikesRequest.SerializeToString,
            statistics__pb2.ViewsAndLikesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/statistics.StatisticsService/GetTopPosts',
            statistics__pb2.TopPostsRequest.SerializeToString,
            statistics__pb2.TopPostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/statistics.StatisticsService/GetTopUsers',
            statistics__pb2.Empty.SerializeToString,
            statistics__pb2.TopUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
