name: Python and Go Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]
        go-version: [1.21.1]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      if: matrix.python-version
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Statistics Unit Tests
      if: matrix.python-version
      run: |
        python -m unittest src/services/statistics/test/unit.py
    - name: Run Users Unit Tests
      if: matrix.python-version
      run: |
        python -m unittest src/services/users/test/unit.py

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Go dependencies
      if: matrix.go-version
      run: |
        cd src/services/posts/app
        if [ -f go.mod ]; then go mod tidy; fi

    - name: Run Go Tests
      if: matrix.go-version
      run: |
        cd src/services/posts/app
        go test ./...
